SELECT * 
FROM STUDENT
ORDER BY REGISTRATIONYEAR;

SELECT * 
FROM EXAMRESULTS
ORDER BY STUDENTID, COURSEID;

SELECT * 
FROM STUDENTATTENDANCE
ORDER BY STUDENTID ;

SELECT * 
FROM DEPARTMENTS
ORDER BY DEPARTMENTID;

SELECT STUDENTID,  (NumberOfDaysOff / (NumberOfWorkingDays + NumberOfDaysOff)) * 100 AS PercentageOff
FROM STUDENTATTENDANCE
ORDER BY PercentageOff DESC;

SELECT ROWNUM AS "BEST GRADE", STUDENTID, COURSEID, GRADE
FROM ( 
    SELECT STUDENTID, COURSEID, GRADE
    FROM EXAMRESULT
    ORDER BY GRADE DESC)
WHERE ROWNUM <= 3;

SELECT * 
FROM PARENTINFORMATION
ORDER BY ParentID ;


